### ISSUE TITLE
Exception in thread "main" picocli.CommandLine$UnmatchedArgumentException

### ISSUE THREAD

**Issue by mmlngl** [kestra-io/deploy-action#12]
Hi, I've set-up a github action as per readme.

I was using `@develop` and deploy was working fine. After upgrading to `@v0.13.0` I get an error.

Here's my Action definition.

```
name: Kestra CI/CD

on: [push]

jobs:
  # Start by validating all kestra resources
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate `app.htch.comms` flows
        uses: kestra-io/validate-action@develop
        with:
          directory: ./apps/kestra/src/lib/flows/comms
          resource: flow

      - name: Validate `app.htch.assets.pipelines` flows
        uses: kestra-io/validate-action@develop
        with:
          directory: ./apps/kestra/src/lib/flows/pipelines
          resource: flow

      - name: Validate `app.htch.assets.transforms` flows
        uses: kestra-io/validate-action@develop
        with:
          directory: ./apps/kestra/src/lib/flows/transforms
          resource: flow

      - name: Validate `app.htch.triggers` flows
        uses: kestra-io/validate-action@develop
        with:
          directory: ./apps/kestra/src/lib/flows/triggers
          resource: flow

      - name: Validate `app.htch.assets.utils` flows
        uses: kestra-io/validate-action@develop
        with:
          directory: ./apps/kestra/src/lib/flows/utils
          resource: flow

  build-dev:
    runs-on: ubuntu-latest
    needs: validate
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: 'Deploy `app.htch.assets.comms` flows'
        uses: kestra-io/deploy-action@develop
        with:
          namespace: app.htch.assets.comms
          directory: ./apps/kestra/src/lib/flows/comms
          resource: flow
          server: ${{ secrets.KESTRA_HOST_DEV }}
          user: ${{ secrets.KESTRA_USER_DEV }}
          password: ${{ secrets.KESTRA_PASSWORD_DEV }}

      - name: 'Deploy `app.htch.assets.pipelines` flows'
        uses: kestra-io/deploy-action@develop
        with:
          namespace: app.htch.assets.pipelines
          directory: ./apps/kestra/src/lib/flows/pipelines
          resource: flow
          server: ${{ secrets.KESTRA_HOST_DEV }}
          user: ${{ secrets.KESTRA_USER_DEV }}
          password: ${{ secrets.KESTRA_PASSWORD_DEV }}

      - name: 'Deploy `app.htch.assets.transforms` flows'
        uses: kestra-io/deploy-action@develop
        with:
          namespace: app.htch.assets.transforms
          directory: ./apps/kestra/src/lib/flows/transforms
          resource: flow
          server: ${{ secrets.KESTRA_HOST_DEV }}
          user: ${{ secrets.KESTRA_USER_DEV }}
          password: ${{ secrets.KESTRA_PASSWORD_DEV }}

      - name: 'Deploy `app.htch.assets.triggers` flows'
        uses: kestra-io/deploy-action@develop
        with:
          namespace: app.htch.assets.triggers
          directory: ./apps/kestra/src/lib/flows/triggers
          resource: flow
          server: ${{ secrets.KESTRA_HOST_DEV }}
          user: ${{ secrets.KESTRA_USER_DEV }}
          password: ${{ secrets.KESTRA_PASSWORD_DEV }}

      - name: 'Deploy `app.htch.assets.utils` flows'
        uses: kestra-io/deploy-action@develop
        with:
          namespace: app.htch.assets.utils
          directory: ./apps/kestra/src/lib/flows/utils
          resource: flow
          server: ${{ secrets.KESTRA_HOST_DEV }}
          user: ${{ secrets.KESTRA_USER_DEV }}
          password: ${{ secrets.KESTRA_PASSWORD_DEV }}

  build-main:
    runs-on: ubuntu-latest
    needs: validate
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: 'Deploy `app.htch.assets.comms` flows'
        uses: kestra-io/deploy-action@develop
        with:
          namespace: app.htch.assets.comms
          directory: ./apps/kestra/src/lib/flows/comms
          resource: flow
          server: ${{ secrets.KESTRA_HOST_MAIN }}
          user: ${{ secrets.KESTRA_USER_MAIN }}
          password: ${{ secrets.KESTRA_PASSWORD_MAIN }}

      - name: 'Deploy `app.htch.assets.pipelines` flows'
        uses: kestra-io/deploy-action@develop
        with:
          namespace: app.htch.assets.pipelines
          directory: ./apps/kestra/src/lib/flows/pipelines
          resource: flow
          server: ${{ secrets.KESTRA_HOST_MAIN }}
          user: ${{ secrets.KESTRA_USER_MAIN }}
          password: ${{ secrets.KESTRA_PASSWORD_MAIN }}

      - name: 'Deploy `app.htch.assets.transforms` flows'
        uses: kestra-io/deploy-action@develop
        with:
          namespace: app.htch.assets.transforms
          directory: ./apps/kestra/src/lib/flows/transforms
          resource: flow
          server: ${{ secrets.KESTRA_HOST_MAIN }}
          user: ${{ secrets.KESTRA_USER_MAIN }}
          password: ${{ secrets.KESTRA_PASSWORD_MAIN }}

      - name: 'Deploy `app.htch.assets.triggers` flows'
        uses: kestra-io/deploy-action@develop
        with:
          namespace: app.htch.assets.triggers
          directory: ./apps/kestra/src/lib/flows/triggers
          resource: flow
          server: ${{ secrets.KESTRA_HOST_MAIN }}
          user: ${{ secrets.KESTRA_USER_MAIN }}
          password: ${{ secrets.KESTRA_PASSWORD_MAIN }}

      - name: 'Deploy `app.htch.assets.utils` flows'
        uses: kestra-io/deploy-action@develop
        with:
          namespace: app.htch.assets.utils
          directory: ./apps/kestra/src/lib/flows/utils
          resource: flow
          server: ${{ secrets.KESTRA_HOST_MAIN }}
          user: ${{ secrets.KESTRA_USER_MAIN }}
          password: ${{ secrets.KESTRA_PASSWORD_MAIN }}

```

And the error is as follows:

```
Exception in thread "main" picocli.CommandLine$UnmatchedArgumentException: Unmatched argument at index 7: ''
	at picocli.CommandLine$Interpreter.validateConstraints(CommandLine.java:[13](https://github.com/HTCH-app/htch/actions/runs/7182088301/job/19557872386#step:4:14)604)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13556)
	at picocli.CommandLine$Interpreter.processSubcommand(CommandLine.java:13842)
	at picocli.CommandLine$Interpreter.processArguments(CommandLine.java:13738)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13533)
	at picocli.CommandLine$Interpreter.processSubcommand(CommandLine.java:13842)
	at picocli.CommandLine$Interpreter.processArguments(CommandLine.java:13738)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13533)
	at picocli.CommandLine$Interpreter.processSubcommand(CommandLine.java:13842)
	at picocli.CommandLine$Interpreter.processArguments(CommandLine.java:13738)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13533)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13501)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13396)
	at picocli.CommandLine.parseArgs(CommandLine.java:[15](https://github.com/HTCH-app/htch/actions/runs/7182088301/job/19557872386#step:4:16)52)
	at io.kestra.cli.App.applicationContext(App.java:94)
	at io.kestra.cli.App.execute(App.java:68)
	at io.kestra.cli.App.main(App.java:51)
	```
