### ISSUE TITLE
GitHub Actions can't find flows cloned from the repository: `java.nio.file.NoSuchFileException: ./flows`

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/deploy-action#2]
I tried the following action:

```yaml
name: Kestra CI/CD
on: 
  workflow_dispatch:
jobs:
  kestra:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: kestra-io/deploy-action@develop
        with:
          namespace: prod
          directory: ./flows/
          resource: flow
          server: ${{secrets.KESTRA_HOST}}
          user: ${{secrets.KESTRA_USER}}
          password: ${{secrets.KESTRA_PASSWORD}}
          delete: false
```

But the flows directory cloned from GitHub repo doesn't seem to get properly mounted to the container: `java.nio.file.NoSuchFileException: ./flows`

![image](https://github.com/kestra-io/deploy-action/assets/86264395/30e705c4-8d0f-4876-b3b9-38009a1c640b)

The helper commands are definitely working because doing all this locally works fine:
![image](https://github.com/kestra-io/deploy-action/assets/86264395/43d3636f-a87d-4a74-baec-e7c07e7d1e25)

But the flows cloned by GitHub runner are not found under "./flows"

**Comment by anna-geller** [comment]
wait, the repository was renamed? it's now without kestra_?

**Comment by anna-geller** [comment]
this fixed the issue:

```yml
name: Kestra CI/CD
on: 
  workflow_dispatch:
jobs:
  kestra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: deploy
        uses: kestra-io/deploy-action@develop
        with:
          namespace: prod
          directory: ./flows
          resource: flow
          server: ${{secrets.KESTRA_HOST}}
          user: ${{secrets.KESTRA_USER}}
          password: ${{secrets.KESTRA_PASSWORD}}
          delete: false
```
